### ISSUE TITLE
Problems with installing Eclipse Plugin

### ISSUE THREAD

**Issue by SwagMuffinMcYoloPants** [bpelunit/bpelunit#23]
I tried installing the plugin using the Install New Software button in Eclipse Neon.3(4.6.3) but I keep getting errors about junit.  

```
Cannot complete the install because one or more required items could not be found.
  Software being installed: BPELUnit Feature 1.6.1 (net.bpelunit.eclipse.feature.feature.group 1.6.1)
  Missing requirement: BPELUnit Eclipse Tool Support Plugin 1.6.1 (net.bpelunit.toolsupport 1.6.1) requires 'bundle org.junit4 0.0.0' but it could not be found
  Cannot satisfy dependency:
    From: BPELUnit Feature 1.6.1 (net.bpelunit.eclipse.feature.feature.group 1.6.1)
    To: net.bpelunit.toolsupport [1.6.1]
```

Is there anyway to fix this?

**Comment by bluezio** [comment]
The update site currently in the BPELUnit website is a bit old: org.junit4 is no longer available in recent Eclipse releases. I have uploaded a zipped update site with a newer version that should install cleanly on Neon.3:

https://github.com/bpelunit/bpelunit/releases/tag/pre-v1.6.2-20170421

Make sure you add the jetty-bundles-8.x update site that is there as well. Please confirm if it works for you and then I'll update the bpelunit.net website as soon as I can.

**Comment by SwagMuffinMcYoloPants** [comment]
Looks like it installs now.  I ran through the Hello World BPEL Unit test minus a few issues where the UI didn't update the underlying BPTS file.  Thank you.

**Comment by bluezio** [comment]
Thanks for the confirmation! I'll close this issue now, but feel free to report anything else you run into :-).
